// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Retail.DAL;

#nullable disable

namespace Retail.DAL.Migrations
{
    [DbContext(typeof(RetailContext))]
    [Migration("20231219180211_v0")]
    partial class v0
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Retail.DAL.Category", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DESCRIPTION")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ID");

                    b.HasIndex("NAME")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            ID = new Guid("c2ae51c9-913a-4e7d-a7b5-ef1efc8f9d3e"),
                            DESCRIPTION = "Experience unparalleled comfort and style with our exquisite collection of furniture. Transform your living spaces with our carefully crafted pieces, designed for both beauty and functionality.",
                            NAME = "Furnitures"
                        },
                        new
                        {
                            ID = new Guid("4b9ad45e-864e-497c-94e8-37dd14027978"),
                            DESCRIPTION = "Step into a world of fashion and comfort with our diverse range of shoes. From casual to formal, our footwear collection is curated to elevate your style and keep you on-trend.",
                            NAME = "Shoes"
                        },
                        new
                        {
                            ID = new Guid("e18e42b7-799e-4b3b-a084-c55d4bb5da3f"),
                            DESCRIPTION = "Explore cutting-edge technology and innovation with our electronic products. Our selection includes high-quality gadgets and devices that are designed to enhance your lifestyle and keep you connected.",
                            NAME = "Electronics"
                        });
                });

            modelBuilder.Entity("Retail.DAL.Product", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CATEGORY_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DESCRIPTION")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PIC")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<decimal>("PRICE")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("QTY")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CATEGORY_ID");

                    b.HasIndex("NAME")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ID = new Guid("7328a266-a10b-4460-a98e-334ecfae1fcf"),
                            CATEGORY_ID = new Guid("c2ae51c9-913a-4e7d-a7b5-ef1efc8f9d3e"),
                            DESCRIPTION = "Very comfortable Silver lounge chair",
                            NAME = "Silver Lounge Chair",
                            PIC = "images/Furniture/Silver Lounge Chair.jpeg",
                            PRICE = 2999m,
                            QTY = 77
                        },
                        new
                        {
                            ID = new Guid("6348d82c-25ad-4ce5-97e0-1176814cbb17"),
                            CATEGORY_ID = new Guid("c2ae51c9-913a-4e7d-a7b5-ef1efc8f9d3e"),
                            DESCRIPTION = "Elegant and comfortable luxury leather sofa.",
                            NAME = "Luxury Leather Sofa",
                            PIC = "images/Furniture/Luxury Leather Sofa.jpeg",
                            PRICE = 1000m,
                            QTY = 0
                        },
                        new
                        {
                            ID = new Guid("185e17f5-4384-44ff-a9ae-8b7a1a95c397"),
                            CATEGORY_ID = new Guid("c2ae51c9-913a-4e7d-a7b5-ef1efc8f9d3e"),
                            DESCRIPTION = "Solid wood dining table set with chairs.",
                            NAME = "Wooden Dining Table Set",
                            PIC = "images/Furniture/Wooden Dining Table Set.jpeg",
                            PRICE = 1499m,
                            QTY = 20
                        },
                        new
                        {
                            ID = new Guid("dd545746-b063-4d11-8187-9e331f179e9e"),
                            CATEGORY_ID = new Guid("c2ae51c9-913a-4e7d-a7b5-ef1efc8f9d3e"),
                            DESCRIPTION = "Very comfortable lounge chair",
                            NAME = "Lounge Chair",
                            PIC = "images/Furniture/Lounge Chair.jpeg",
                            PRICE = 999m,
                            QTY = 10
                        },
                        new
                        {
                            ID = new Guid("d4a30a75-7605-4c3a-8188-cf6152a397dc"),
                            CATEGORY_ID = new Guid("c2ae51c9-913a-4e7d-a7b5-ef1efc8f9d3e"),
                            DESCRIPTION = "Very comfortable pink leather office chair",
                            NAME = "Pink Leather Office Chair",
                            PIC = "images/Furniture/Pink Leather Office Chair.jpeg",
                            PRICE = 4999m,
                            QTY = 56
                        },
                        new
                        {
                            ID = new Guid("bbfa55f0-9a83-405a-b2b4-bcff04cb8815"),
                            CATEGORY_ID = new Guid("4b9ad45e-864e-497c-94e8-37dd14027978"),
                            DESCRIPTION = "High-performance running shoes for men.",
                            NAME = "Running Shoes - Men",
                            PIC = "images/Shoes/Running Shoes - Men.jpeg",
                            PRICE = 299m,
                            QTY = 58
                        },
                        new
                        {
                            ID = new Guid("53483415-caf8-4b0b-a6ca-880c7eeac0d3"),
                            CATEGORY_ID = new Guid("4b9ad45e-864e-497c-94e8-37dd14027978"),
                            DESCRIPTION = "Stylish and comfortable casual sneakers for women",
                            NAME = "Casual Sneakers - Women",
                            PIC = "images/Shoes/Casual Sneakers - Women.jpeg",
                            PRICE = 499m,
                            QTY = 0
                        },
                        new
                        {
                            ID = new Guid("b69cbb1b-6b05-44fa-941b-ce380fb2a00d"),
                            CATEGORY_ID = new Guid("4b9ad45e-864e-497c-94e8-37dd14027978"),
                            DESCRIPTION = "Classic leather boots suitable for both men and women.",
                            NAME = "Leather Boots - Unisex",
                            PIC = "images/Shoes/Leather Boots - Unisex.jpeg",
                            PRICE = 334m,
                            QTY = 95
                        },
                        new
                        {
                            ID = new Guid("eb473be4-b132-4208-8a70-87a5b2031f78"),
                            CATEGORY_ID = new Guid("4b9ad45e-864e-497c-94e8-37dd14027978"),
                            DESCRIPTION = "Comfortable sandals designed for arch support",
                            NAME = "Sandals with Arch Support",
                            PIC = "images/Shoes/Sandals with Arch Support.jpeg",
                            PRICE = 99m,
                            QTY = 90
                        },
                        new
                        {
                            ID = new Guid("1f1eb7aa-2f9d-4dd5-852b-58458b880aba"),
                            CATEGORY_ID = new Guid("4b9ad45e-864e-497c-94e8-37dd14027978"),
                            DESCRIPTION = "Elegant formal shoes for men.",
                            NAME = "Formal Shoes - Men",
                            PIC = "images/Shoes/Formal Shoes - Men.jpeg",
                            PRICE = 699m,
                            QTY = 145
                        },
                        new
                        {
                            ID = new Guid("e0d0da98-21c4-4a75-9804-3b5c8ba5682b"),
                            CATEGORY_ID = new Guid("e18e42b7-799e-4b3b-a084-c55d4bb5da3f"),
                            DESCRIPTION = "Canon Digital Camera - High quality digital camera provided by Canon",
                            NAME = "Canon Digital Camera",
                            PIC = "images/Electronic/Canon Digital Camera.jpeg",
                            PRICE = 9999m,
                            QTY = 8
                        },
                        new
                        {
                            ID = new Guid("1375aec5-624f-49cd-86d7-56e88db3d17e"),
                            CATEGORY_ID = new Guid("e18e42b7-799e-4b3b-a084-c55d4bb5da3f"),
                            DESCRIPTION = "Complete smart home security solution.",
                            NAME = "Smart Home Security System",
                            PIC = "images/Electronic/Smart Home Security System.jpeg",
                            PRICE = 29999m,
                            QTY = 0
                        },
                        new
                        {
                            ID = new Guid("b870ddcd-5ebe-4270-8db0-d85f4b5f9f9a"),
                            CATEGORY_ID = new Guid("e18e42b7-799e-4b3b-a084-c55d4bb5da3f"),
                            DESCRIPTION = "Professional digital camera with accessories.",
                            NAME = "Digital Camera Kit",
                            PIC = "images/Electronic/Digital Camera Kit.jpeg",
                            PRICE = 19999m,
                            QTY = 15
                        },
                        new
                        {
                            ID = new Guid("a8d78681-f5c9-4041-9c50-1f9876447369"),
                            CATEGORY_ID = new Guid("e18e42b7-799e-4b3b-a084-c55d4bb5da3f"),
                            DESCRIPTION = "Sennheiser Digital Camera - High quality digital camera provided by Sennheiser - includes tripod",
                            NAME = "Sennheiser Digital Camera with Tripod",
                            PIC = "images/Electronic/Sennheiser Digital Camera with Tripod.jpeg",
                            PRICE = 14999m,
                            QTY = 20
                        },
                        new
                        {
                            ID = new Guid("3d10d175-f156-48e6-8443-eb06324b55b6"),
                            CATEGORY_ID = new Guid("e18e42b7-799e-4b3b-a084-c55d4bb5da3f"),
                            DESCRIPTION = "On-ear Black Headphones - these headphones are not wireless",
                            NAME = "On-ear Black Headphones",
                            PIC = "images/Electronic/On-ear Black Headphones.jpeg",
                            PRICE = 9977m,
                            QTY = 37
                        });
                });

            modelBuilder.Entity("Retail.DAL.Product", b =>
                {
                    b.HasOne("Retail.DAL.Category", "CATEGORY")
                        .WithMany("PRODUCTS")
                        .HasForeignKey("CATEGORY_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CATEGORY");
                });

            modelBuilder.Entity("Retail.DAL.Category", b =>
                {
                    b.Navigation("PRODUCTS");
                });
#pragma warning restore 612, 618
        }
    }
}
