// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Retail.DAL;

#nullable disable

namespace Retail.DAL.Migrations
{
    [DbContext(typeof(RetailContext))]
    [Migration("20231219180104_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Retail.DAL.Category", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DESCRIPTION")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ID");

                    b.HasIndex("NAME")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            ID = new Guid("c2ae51c9-913a-4e7d-a7b5-ef1efc8f9d3e"),
                            DESCRIPTION = "Experience unparalleled comfort and style with our exquisite collection of furniture. Transform your living spaces with our carefully crafted pieces, designed for both beauty and functionality.",
                            NAME = "Furnitures"
                        },
                        new
                        {
                            ID = new Guid("4b9ad45e-864e-497c-94e8-37dd14027978"),
                            DESCRIPTION = "Step into a world of fashion and comfort with our diverse range of shoes. From casual to formal, our footwear collection is curated to elevate your style and keep you on-trend.",
                            NAME = "Shoes"
                        },
                        new
                        {
                            ID = new Guid("e18e42b7-799e-4b3b-a084-c55d4bb5da3f"),
                            DESCRIPTION = "Explore cutting-edge technology and innovation with our electronic products. Our selection includes high-quality gadgets and devices that are designed to enhance your lifestyle and keep you connected.",
                            NAME = "Electronics"
                        });
                });

            modelBuilder.Entity("Retail.DAL.Product", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CATEGORY_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DESCRIPTION")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PIC")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<decimal>("PRICE")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("QTY")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CATEGORY_ID");

                    b.HasIndex("NAME")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ID = new Guid("76defb07-47c0-437c-a58e-2b1cdf012057"),
                            CATEGORY_ID = new Guid("c2ae51c9-913a-4e7d-a7b5-ef1efc8f9d3e"),
                            DESCRIPTION = "Very comfortable Silver lounge chair",
                            NAME = "Silver Lounge Chair",
                            PIC = "images/Furniture/Silver Lounge Chair.jpeg",
                            PRICE = 2999m,
                            QTY = 77
                        },
                        new
                        {
                            ID = new Guid("ce8490af-5fd6-4f45-afff-b81db2a5c1dd"),
                            CATEGORY_ID = new Guid("c2ae51c9-913a-4e7d-a7b5-ef1efc8f9d3e"),
                            DESCRIPTION = "Elegant and comfortable luxury leather sofa.",
                            NAME = "Luxury Leather Sofa",
                            PIC = "images/Furniture/Luxury Leather Sofa.jpeg",
                            PRICE = 1000m,
                            QTY = 0
                        },
                        new
                        {
                            ID = new Guid("eaaee255-7eef-4b21-9660-36f5f6e7bf77"),
                            CATEGORY_ID = new Guid("c2ae51c9-913a-4e7d-a7b5-ef1efc8f9d3e"),
                            DESCRIPTION = "Solid wood dining table set with chairs.",
                            NAME = "Wooden Dining Table Set",
                            PIC = "images/Furniture/Wooden Dining Table Set.jpeg",
                            PRICE = 1499m,
                            QTY = 20
                        },
                        new
                        {
                            ID = new Guid("74495e9d-7feb-4ac5-90b6-54b86c25711f"),
                            CATEGORY_ID = new Guid("c2ae51c9-913a-4e7d-a7b5-ef1efc8f9d3e"),
                            DESCRIPTION = "Very comfortable lounge chair",
                            NAME = "Lounge Chair",
                            PIC = "images/Furniture/Lounge Chair.jpeg",
                            PRICE = 999m,
                            QTY = 10
                        },
                        new
                        {
                            ID = new Guid("258d4faf-cfba-40be-bf12-759e376de126"),
                            CATEGORY_ID = new Guid("c2ae51c9-913a-4e7d-a7b5-ef1efc8f9d3e"),
                            DESCRIPTION = "Very comfortable pink leather office chair",
                            NAME = "Pink Leather Office Chair",
                            PIC = "images/Furniture/Pink Leather Office Chair.jpeg",
                            PRICE = 4999m,
                            QTY = 56
                        },
                        new
                        {
                            ID = new Guid("cc71f8f9-d5ca-42e9-a92c-ef1e1fb2a3ac"),
                            CATEGORY_ID = new Guid("4b9ad45e-864e-497c-94e8-37dd14027978"),
                            DESCRIPTION = "High-performance running shoes for men.",
                            NAME = "Running Shoes - Men",
                            PIC = "images/Shoes/Running Shoes - Men.jpeg",
                            PRICE = 299m,
                            QTY = 58
                        },
                        new
                        {
                            ID = new Guid("9b030847-9e86-4eae-8779-c2aa3d8b16bb"),
                            CATEGORY_ID = new Guid("4b9ad45e-864e-497c-94e8-37dd14027978"),
                            DESCRIPTION = "Stylish and comfortable casual sneakers for women",
                            NAME = "Casual Sneakers - Women",
                            PIC = "images/Shoes/Casual Sneakers - Women.jpeg",
                            PRICE = 499m,
                            QTY = 0
                        },
                        new
                        {
                            ID = new Guid("16872cb4-4a80-46c5-b0ef-cea3f6a91c5d"),
                            CATEGORY_ID = new Guid("4b9ad45e-864e-497c-94e8-37dd14027978"),
                            DESCRIPTION = "Classic leather boots suitable for both men and women.",
                            NAME = "Leather Boots - Unisex",
                            PIC = "images/Shoes/Leather Boots - Unisex.jpeg",
                            PRICE = 334m,
                            QTY = 95
                        },
                        new
                        {
                            ID = new Guid("2a199636-d4fc-419c-b3ad-80943acc3fff"),
                            CATEGORY_ID = new Guid("4b9ad45e-864e-497c-94e8-37dd14027978"),
                            DESCRIPTION = "Comfortable sandals designed for arch support",
                            NAME = "Sandals with Arch Support",
                            PIC = "images/Shoes/Sandals with Arch Support.jpeg",
                            PRICE = 99m,
                            QTY = 90
                        },
                        new
                        {
                            ID = new Guid("3793aea2-8c7e-423d-ba29-1ef786a75a10"),
                            CATEGORY_ID = new Guid("4b9ad45e-864e-497c-94e8-37dd14027978"),
                            DESCRIPTION = "Elegant formal shoes for men.",
                            NAME = "Formal Shoes - Men",
                            PIC = "images/Shoes/Formal Shoes - Men.jpeg",
                            PRICE = 699m,
                            QTY = 145
                        },
                        new
                        {
                            ID = new Guid("1be78c53-77d7-4a95-85fa-dc63e744018e"),
                            CATEGORY_ID = new Guid("e18e42b7-799e-4b3b-a084-c55d4bb5da3f"),
                            DESCRIPTION = "Canon Digital Camera - High quality digital camera provided by Canon",
                            NAME = "Canon Digital Camera",
                            PIC = "images/Electronic/Canon Digital Camera.jpeg",
                            PRICE = 9999m,
                            QTY = 8
                        },
                        new
                        {
                            ID = new Guid("d997d404-7986-44cb-ad46-2e2a6d8cd811"),
                            CATEGORY_ID = new Guid("e18e42b7-799e-4b3b-a084-c55d4bb5da3f"),
                            DESCRIPTION = "Complete smart home security solution.",
                            NAME = "Smart Home Security System",
                            PIC = "images/Electronic/Smart Home Security System.jpeg",
                            PRICE = 29999m,
                            QTY = 0
                        },
                        new
                        {
                            ID = new Guid("3b349230-e864-4cce-a853-0063529fdf38"),
                            CATEGORY_ID = new Guid("e18e42b7-799e-4b3b-a084-c55d4bb5da3f"),
                            DESCRIPTION = "Professional digital camera with accessories.",
                            NAME = "Digital Camera Kit",
                            PIC = "images/Electronic/Digital Camera Kit.jpeg",
                            PRICE = 19999m,
                            QTY = 15
                        },
                        new
                        {
                            ID = new Guid("b1295cdf-d372-471a-b28f-7636749453d2"),
                            CATEGORY_ID = new Guid("e18e42b7-799e-4b3b-a084-c55d4bb5da3f"),
                            DESCRIPTION = "Sennheiser Digital Camera - High quality digital camera provided by Sennheiser - includes tripod",
                            NAME = "Sennheiser Digital Camera with Tripod",
                            PIC = "images/Electronic/Sennheiser Digital Camera with Tripod.jpeg",
                            PRICE = 14999m,
                            QTY = 20
                        },
                        new
                        {
                            ID = new Guid("e70f97c3-9d56-42a8-bc42-989cf7300757"),
                            CATEGORY_ID = new Guid("e18e42b7-799e-4b3b-a084-c55d4bb5da3f"),
                            DESCRIPTION = "On-ear Black Headphones - these headphones are not wireless",
                            NAME = "On-ear Black Headphones",
                            PIC = "images/Electronic/On-ear Black Headphones.jpeg",
                            PRICE = 9977m,
                            QTY = 37
                        });
                });

            modelBuilder.Entity("Retail.DAL.Product", b =>
                {
                    b.HasOne("Retail.DAL.Category", "CATEGORY")
                        .WithMany("PRODUCTS")
                        .HasForeignKey("CATEGORY_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CATEGORY");
                });

            modelBuilder.Entity("Retail.DAL.Category", b =>
                {
                    b.Navigation("PRODUCTS");
                });
#pragma warning restore 612, 618
        }
    }
}
